/**
 * Legacy OpenAI service — Budget Bracket ONLY.
 *
 * Retitled, Cast Climb, and Poster Pixels are now generated by the modular
 * `lib/puzzle-generator` module (per GH issue #55). This file intentionally
 * retains only the Budget Bracket path and the `getRecentMovieIds` helper
 * that path depends on, so the Budget Bracket admin UI (out of scope for
 * #55) keeps working exactly as it did.
 *
 * Anything in here should be considered frozen — new work should live in
 * `lib/puzzle-generator/*` + `lib/ai/openai-responses.ts`.
 */

import { TMDBMovie, TMDBMovieDetails } from './types/tmdb'
import { getMovieById } from './tmdb'

const OPENAI_API_KEY = process.env.OPENAI_API_KEY

export interface GenerationConfig {
  /** Percentage difference allowed between paired budgets (e.g. 0.3 = 30%). */
  budgetClosenessThreshold?: number
  /** Days to look back for any game type (default 30). */
  avoidRecentDays?: number
  /** Days to look back for same game type (default 365). */
  avoidSameGameDays?: number
}

export interface SmartPuzzleRequest {
  gameType: 'budget-bracket'
  targetDate: string
  config?: GenerationConfig
}

export interface SmartPuzzleResponse {
  success: boolean
  puzzle?: any
  error?: string
  suggestions?: TMDBMovie[]
}

const DEFAULT_CONFIG: Required<GenerationConfig> = {
  budgetClosenessThreshold: 0.3,
  avoidRecentDays: 30,
  avoidSameGameDays: 365,
}

async function queryOpenAIForMovies(
  gameType: string,
  prompt: string,
): Promise<number[]> {
  if (!OPENAI_API_KEY) {
    throw new Error('OpenAI API key not configured')
  }

  const response = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      Authorization: `Bearer ${OPENAI_API_KEY}`,
    },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: `You are a movie puzzle generator assistant for the game "${gameType}". Return a JSON object with a "movie_ids" field containing an array of TMDB movie ID numbers, for example {"movie_ids": [550, 680, 155, 27205, 13]}.`,
        },
        { role: 'user', content: prompt },
      ],
      temperature: 0.7,
      max_tokens: 1000,
      response_format: { type: 'json_object' },
    }),
  })

  if (!response.ok) {
    throw new Error(`OpenAI API error: ${response.status}`)
  }

  const data = await response.json()
  const content = data.choices?.[0]?.message?.content || '{}'
  let parsed: any
  try {
    parsed = JSON.parse(content)
  } catch {
    throw new Error('Invalid JSON response from OpenAI')
  }
  const movieIds = parsed.movie_ids || parsed.movies || parsed.ids || []
  if (!Array.isArray(movieIds)) {
    throw new Error('Invalid response format from OpenAI')
  }
  return movieIds
}

async function generateBudgetBracketPuzzle(
  targetDate: string,
  config: Required<GenerationConfig>,
  recentMovieIds: number[],
): Promise<any> {
  const pairs: Array<Array<Record<string, unknown>>> = []
  const usedMovieIds = new Set<number>()

  for (let round = 1; round <= 5; round++) {
    const prompt = `Find pairs of movies with interesting budget comparisons for round ${round}.
    The budgets should be within ${(config.budgetClosenessThreshold * 100).toFixed(0)}% of each other.
    Focus on movies where the budget might be surprising.
    Avoid these movie IDs: ${[...recentMovieIds, ...Array.from(usedMovieIds)].join(', ')}.
    Return 4 movie TMDB IDs.`

    const movieIds = await queryOpenAIForMovies('budget-bracket', prompt)

    const validMovies: TMDBMovieDetails[] = []
    for (const id of movieIds) {
      const movie = (await getMovieById(id)) as TMDBMovieDetails
      if (movie && movie.budget && movie.budget > 0 && !usedMovieIds.has(id)) {
        validMovies.push(movie)
        usedMovieIds.add(id)
      }
    }

    if (validMovies.length >= 2) {
      validMovies.sort((a, b) => (a.budget || 0) - (b.budget || 0))
      for (let i = 0; i < validMovies.length - 1; i++) {
        const m1 = validMovies[i]
        const m2 = validMovies[i + 1]
        const ratio = (m2.budget || 0) / (m1.budget || 1)
        if (ratio <= 1 + config.budgetClosenessThreshold) {
          pairs.push([
            {
              id: m1.id,
              title: m1.title,
              poster_path: m1.poster_path,
              release_date: m1.release_date,
              budget: m1.budget,
            },
            {
              id: m2.id,
              title: m2.title,
              poster_path: m2.poster_path,
              release_date: m2.release_date,
              budget: m2.budget,
            },
          ])
          break
        }
      }
    }
  }

  if (pairs.length < 5) {
    throw new Error('Could not generate enough movie pairs for Budget Bracket')
  }

  return {
    puzzle_date: targetDate,
    seed_value: Math.random().toString(36).substring(2, 15),
    pairs,
  }
}

/**
 * Generate a Budget Bracket puzzle via the legacy OpenAI chat-completions
 * flow. Do NOT call this for retitled / cast-climb / poster-pixels; those
 * now live in `lib/puzzle-generator`.
 */
export async function generateSmartPuzzle(
  request: SmartPuzzleRequest,
  recentMovieIds: number[] = [],
): Promise<SmartPuzzleResponse> {
  if (request.gameType !== 'budget-bracket') {
    return {
      success: false,
      error:
        'generateSmartPuzzle is legacy-only and supports budget-bracket; call generatePuzzle() from lib/puzzle-generator for other games.',
    }
  }

  const config = { ...DEFAULT_CONFIG, ...request.config }

  try {
    const puzzle = await generateBudgetBracketPuzzle(
      request.targetDate,
      config,
      recentMovieIds,
    )
    return { success: true, puzzle }
  } catch (error) {
    console.error('Error generating budget-bracket puzzle:', error)

    const fallbackPrompt =
      'Suggest 5 popular movies with public budget info that would work for a budget-comparison game. Return TMDB IDs.'
    try {
      const suggestionIds = await queryOpenAIForMovies(
        'budget-bracket',
        fallbackPrompt,
      )
      const suggestions: TMDBMovie[] = []
      for (const id of suggestionIds) {
        const movie = await getMovieById(id)
        if (movie) suggestions.push(movie as TMDBMovie)
      }
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
        suggestions,
      }
    } catch {
      return {
        success: false,
        error: error instanceof Error ? error.message : 'Unknown error',
      }
    }
  }
}

/**
 * Collect film ids used in puzzles within the last N days.
 *
 * Still used by the budget-bracket path in
 * `app/api/admin/puzzles/generate/route.ts`. The new `lib/puzzle-generator`
 * has a more structured `buildExclusionSet` helper.
 */
export async function getRecentMovieIds(
  supabase: any,
  gameType?: string,
  daysBack: number = 30,
): Promise<number[]> {
  const cutoffDate = new Date()
  cutoffDate.setDate(cutoffDate.getDate() - daysBack)
  const cutoffDateStr = cutoffDate.toISOString().split('T')[0]

  const movieIds = new Set<number>()

  const tables = gameType
    ? [`${gameType.replace('-', '_')}_puzzles`]
    : [
        'retitled_puzzles',
        'budget_bracket_puzzles',
        'cast_climb_puzzles',
        'poster_pixels_puzzles',
      ]

  for (const table of tables) {
    const { data, error } = await supabase
      .from(table)
      .select('film_id, pairs')
      .gte('puzzle_date', cutoffDateStr)

    if (!error && data) {
      for (const row of data as Array<Record<string, unknown>>) {
        if (typeof row.film_id === 'number') {
          movieIds.add(row.film_id)
        }
        if (Array.isArray(row.pairs)) {
          for (const pair of row.pairs) {
            if (!Array.isArray(pair)) continue
            for (const movie of pair) {
              const mid = (movie as any)?.id
              if (typeof mid === 'number') movieIds.add(mid)
            }
          }
        }
      }
    }
  }

  return Array.from(movieIds)
}
