/**
 * Eligibility & exclusion logic for the smart puzzle generator.
 *
 * "Eligibility" for us means two things:
 *
 *  1. Membership filter (exclusion set): a movie must not be in this set.
 *     - Rule A: film was ever used in the SAME game (film_id appears in
 *               that game's puzzles table).
 *     - Rule B: film was used in ANY game in the last N days (default 30,
 *               per issue #55). This includes the `pairs` array inside
 *               `budget_bracket_puzzles`.
 *
 *  2. Quality filter (`isMovieAppropriate`): minimum TMDB vote count, poster
 *     presence, not adult, released between 1960 and current year.
 *
 * Save-time guards live in `app/api/admin/puzzles/save/route.ts`; the
 * generator runs the same checks up-front so the dialog never hands the
 * editor an ineligible puzzle.
 */

import type { SupabaseClient } from '@supabase/supabase-js'
import type { TMDBMovie, TMDBMovieDetails } from '@/lib/types/tmdb'
import type { PuzzleGameType } from './types'

/** Map our dash-form game types to the underscore-form puzzles table names. */
const GAME_TYPE_TO_TABLE: Record<PuzzleGameType, string> = {
  retitled: 'retitled_puzzles',
  'cast-climb': 'cast_climb_puzzles',
  'poster-pixels': 'poster_pixels_puzzles',
}

/** Tables we scan for the "any game, last N days" rule. Budget bracket is here
 *  even though it's not generated by this module, because a movie used in a
 *  recent BB puzzle should still block the smart generator from reusing it. */
const ANY_GAME_TABLES = [
  'retitled_puzzles',
  'cast_climb_puzzles',
  'poster_pixels_puzzles',
  'budget_bracket_puzzles',
] as const

export interface BuildExclusionSetOptions {
  gameType: PuzzleGameType
  /** Number of days back the "any game" window extends. Must be >= 30. */
  avoidRecentDays: number
  /** Optional extra ids to merge (e.g. callback-accumulated ids for bulk runs). */
  extraExclusions?: readonly number[]
}

export interface ExclusionSetResult {
  ids: Set<number>
  counts: {
    sameGameEver: number
    anyGameRecent: number
    extra: number
  }
}

/**
 * Build the combined exclusion set. Always uses the service-role client the
 * caller passes in so RLS doesn't hide rows.
 */
export async function buildExclusionSet(
  supabase: SupabaseClient,
  options: BuildExclusionSetOptions,
): Promise<ExclusionSetResult> {
  const ids = new Set<number>()
  const counts = { sameGameEver: 0, anyGameRecent: 0, extra: 0 }

  const sameGameTable = GAME_TYPE_TO_TABLE[options.gameType]
  const { data: sameGameRows, error: sameGameErr } = await supabase
    .from(sameGameTable)
    .select('film_id')
  if (sameGameErr) {
    throw new Error(
      `Failed to read ${sameGameTable} for same-game exclusion: ${sameGameErr.message}`,
    )
  }
  for (const row of sameGameRows ?? []) {
    if (typeof (row as any).film_id === 'number') {
      ids.add((row as any).film_id)
      counts.sameGameEver += 1
    }
  }

  const cutoff = new Date()
  cutoff.setUTCDate(cutoff.getUTCDate() - options.avoidRecentDays)
  const cutoffDateStr = cutoff.toISOString().split('T')[0]

  for (const table of ANY_GAME_TABLES) {
    const selectCols = table === 'budget_bracket_puzzles' ? 'pairs' : 'film_id'
    const { data, error } = await supabase
      .from(table)
      .select(selectCols)
      .gte('puzzle_date', cutoffDateStr)
    if (error) {
      console.warn(
        `[puzzle-generator] failed to read ${table} for recent-window check: ${error.message}`,
      )
      continue
    }
    for (const row of (data ?? []) as any[]) {
      if (typeof row.film_id === 'number') {
        if (!ids.has(row.film_id)) counts.anyGameRecent += 1
        ids.add(row.film_id)
      }
      if (Array.isArray(row.pairs)) {
        for (const pair of row.pairs) {
          if (!Array.isArray(pair)) continue
          for (const movie of pair) {
            const mid = (movie as any)?.id
            if (typeof mid === 'number') {
              if (!ids.has(mid)) counts.anyGameRecent += 1
              ids.add(mid)
            }
          }
        }
      }
    }
  }

  for (const id of options.extraExclusions ?? []) {
    if (typeof id === 'number' && !ids.has(id)) {
      ids.add(id)
      counts.extra += 1
    }
  }

  return { ids, counts }
}

export interface RecencyConflict {
  gameType: PuzzleGameType | 'budget-bracket'
  puzzleDate: string
}

/**
 * Return the first conflicting usage of `filmId` within ±N days of
 * `targetDate` across every in-scope puzzles table — or null if the film is
 * clear. Used by the save route to enforce the "not used in any game type in
 * the last 30 days" rule from GH #55.
 *
 * We use a two-sided window (before AND after) because the admin may be
 * scheduling puzzles out of order; either direction constitutes a conflict.
 */
export async function findRecencyConflict(
  supabase: SupabaseClient,
  filmId: number,
  targetDate: string,
  options: { windowDays: number; excludePuzzle?: { table: string; id: string } },
): Promise<RecencyConflict | null> {
  const target = new Date(`${targetDate}T00:00:00Z`)
  if (Number.isNaN(target.getTime())) return null
  const start = new Date(target)
  start.setUTCDate(start.getUTCDate() - options.windowDays)
  const end = new Date(target)
  end.setUTCDate(end.getUTCDate() + options.windowDays)
  const startStr = start.toISOString().slice(0, 10)
  const endStr = end.toISOString().slice(0, 10)

  const singleFilmTables: Array<{ table: string; gameType: PuzzleGameType }> = [
    { table: 'retitled_puzzles', gameType: 'retitled' },
    { table: 'cast_climb_puzzles', gameType: 'cast-climb' },
    { table: 'poster_pixels_puzzles', gameType: 'poster-pixels' },
  ]
  for (const { table, gameType } of singleFilmTables) {
    let query = supabase
      .from(table)
      .select('id, puzzle_date')
      .eq('film_id', filmId)
      .gte('puzzle_date', startStr)
      .lte('puzzle_date', endStr)
      .limit(1)
    if (options.excludePuzzle?.table === table) {
      query = query.neq('id', options.excludePuzzle.id)
    }
    const { data, error } = await query
    if (error) {
      console.warn(
        `[puzzle-generator] findRecencyConflict: failed to read ${table}: ${error.message}`,
      )
      continue
    }
    if (data && data.length > 0) {
      return { gameType, puzzleDate: (data[0] as any).puzzle_date }
    }
  }

  const { data: bbRows, error: bbErr } = await supabase
    .from('budget_bracket_puzzles')
    .select('id, puzzle_date, pairs')
    .gte('puzzle_date', startStr)
    .lte('puzzle_date', endStr)
  if (bbErr) {
    console.warn(
      `[puzzle-generator] findRecencyConflict: failed to read budget_bracket_puzzles: ${bbErr.message}`,
    )
  } else {
    for (const row of (bbRows ?? []) as any[]) {
      if (
        options.excludePuzzle?.table === 'budget_bracket_puzzles' &&
        row.id === options.excludePuzzle.id
      ) {
        continue
      }
      if (!Array.isArray(row.pairs)) continue
      for (const pair of row.pairs) {
        if (!Array.isArray(pair)) continue
        for (const movie of pair) {
          const mid = (movie as any)?.id
          if (typeof mid === 'number' && mid === filmId) {
            return { gameType: 'budget-bracket', puzzleDate: row.puzzle_date }
          }
        }
      }
    }
  }

  return null
}

/**
 * Build a human-readable explanation for why `filmId` is currently in the
 * exclusion set for `gameType`. Walks every puzzles table looking for the
 * most recent usage of the film and describes that usage in a sentence an
 * admin can act on (e.g. "Already used in retitled on 2025-11-04").
 *
 * Used by the orchestrator when `forcedFilmId` is excluded: we short-circuit
 * with an `exclusion_conflict` event and include this reason string so the
 * admin UI doesn't have to replicate the lookup.
 */
export async function describeExclusionReason(
  supabase: SupabaseClient,
  filmId: number,
  options: { gameType: PuzzleGameType; avoidRecentDays: number },
): Promise<string> {
  const sameGameTable = GAME_TYPE_TO_TABLE[options.gameType]
  const { data: sameRows, error: sameErr } = await supabase
    .from(sameGameTable)
    .select('puzzle_date')
    .eq('film_id', filmId)
    .order('puzzle_date', { ascending: false })
    .limit(1)
  if (!sameErr && sameRows && sameRows.length > 0) {
    const date = (sameRows[0] as any).puzzle_date
    return `Already used in ${options.gameType} on ${date}. A film can only appear in the same game once.`
  }

  const cutoff = new Date()
  cutoff.setUTCDate(cutoff.getUTCDate() - options.avoidRecentDays)
  const cutoffDateStr = cutoff.toISOString().slice(0, 10)

  let latest: { gameType: PuzzleGameType | 'budget-bracket'; date: string } | null = null
  for (const table of ANY_GAME_TABLES) {
    if (table === 'budget_bracket_puzzles') {
      const { data, error } = await supabase
        .from(table)
        .select('puzzle_date, pairs')
        .gte('puzzle_date', cutoffDateStr)
        .order('puzzle_date', { ascending: false })
      if (error) continue
      for (const row of (data ?? []) as any[]) {
        if (!Array.isArray(row.pairs)) continue
        const has = row.pairs.some(
          (pair: any) =>
            Array.isArray(pair) && pair.some((m: any) => m?.id === filmId),
        )
        if (has) {
          if (!latest || row.puzzle_date > latest.date) {
            latest = { gameType: 'budget-bracket', date: row.puzzle_date }
          }
          break
        }
      }
    } else {
      const gameType: PuzzleGameType =
        table === 'retitled_puzzles'
          ? 'retitled'
          : table === 'cast_climb_puzzles'
            ? 'cast-climb'
            : 'poster-pixels'
      const { data, error } = await supabase
        .from(table)
        .select('puzzle_date')
        .eq('film_id', filmId)
        .gte('puzzle_date', cutoffDateStr)
        .order('puzzle_date', { ascending: false })
        .limit(1)
      if (error) continue
      const row = (data ?? [])[0] as any
      if (row?.puzzle_date) {
        if (!latest || row.puzzle_date > latest.date) {
          latest = { gameType, date: row.puzzle_date }
        }
      }
    }
  }

  if (latest) {
    return `Used in ${latest.gameType} on ${latest.date}, within the last ${options.avoidRecentDays} days. A film can't appear in any game within that window.`
  }

  return `This film is currently excluded from ${options.gameType}. It may have been added to the exclusion list manually.`
}

export interface VoteCountOptions {
  /**
   * Minimum TMDB vote_count a film must have. Films with fewer are rejected.
   * Use 0 to disable the vote-count filter entirely.
   */
  minVoteCount: number
}

/**
 * Full gate: vote-count + poster + adult + release-year guards.
 */
export function isMovieAppropriate(
  movie: TMDBMovie | TMDBMovieDetails,
  options: VoteCountOptions,
): boolean {
  return describeIneligibility(movie, options) === null
}

/**
 * Like `isMovieAppropriate`, but returns a specific reason on failure (or
 * null if the movie passes every gate). Used by the strategies so the
 * `Activity` log in the smart-generation dialog tells the admin which
 * filter rejected each candidate instead of a vague generic message.
 */
export function describeIneligibility(
  movie: TMDBMovie | TMDBMovieDetails,
  options: VoteCountOptions,
): string | null {
  const votes = movie.vote_count ?? 0
  if (options.minVoteCount > 0 && votes < options.minVoteCount) {
    return `Only ${votes.toLocaleString()} TMDB votes (minimum ${options.minVoteCount.toLocaleString()}). Lower the minimum vote count to include this.`
  }
  if (!movie.poster_path) {
    return 'No poster image on TMDB.'
  }
  if (movie.adult) {
    return 'Marked as adult content on TMDB.'
  }
  if (movie.release_date) {
    const releaseYear = new Date(movie.release_date).getUTCFullYear()
    const currentYear = new Date().getUTCFullYear()
    if (Number.isNaN(releaseYear)) {
      return `Unparseable release date "${movie.release_date}".`
    }
    if (releaseYear < 1960) {
      return `Released ${releaseYear} (before the 1960 cutoff).`
    }
    if (releaseYear > currentYear) {
      return `Released ${releaseYear} (in the future).`
    }
  }
  return null
}
