-- Consolidated Poster Pixels migration
-- Includes: initial tables, admin fields, movie_data fix, and zoom backfill adjustments

BEGIN;

-- 1) Base tables
CREATE TABLE IF NOT EXISTS "public"."poster_pixels_puzzles" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "puzzle_date" date,
  "movie_data" jsonb,
  "created_at" timestamp with time zone DEFAULT now(),
  "updated_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."poster_pixels_games" (
  "id" uuid DEFAULT gen_random_uuid() NOT NULL,
  "user_id" uuid NOT NULL,
  "puzzle_id" bigint NOT NULL,
  "start_time" timestamp with time zone NOT NULL,
  "end_time" timestamp with time zone,
  "completed" boolean DEFAULT false,
  "won" boolean DEFAULT false,
  "total_time_ms" integer,
  "num_guesses" integer DEFAULT 0,
  "final_clarity_level" numeric(5,2),
  "created_at" timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS "public"."poster_pixels_guesses" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "user_id" uuid NOT NULL,
  "puzzle_id" bigint NOT NULL,
  "game_id" uuid NOT NULL,
  "guess_number" integer NOT NULL,
  "guessed_movie_id" integer,
  "guessed_movie_title" text,
  "is_correct" boolean NOT NULL,
  "time_taken_ms" integer NOT NULL,
  "clarity_level" numeric(5,2) NOT NULL,
  "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."poster_pixels_puzzles" OWNER TO "postgres";
ALTER TABLE "public"."poster_pixels_games" OWNER TO "postgres";
ALTER TABLE "public"."poster_pixels_guesses" OWNER TO "postgres";

-- Primary keys (only add if missing)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'poster_pixels_puzzles_pkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_puzzles"
      ADD CONSTRAINT "poster_pixels_puzzles_pkey" PRIMARY KEY ("id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'poster_pixels_games_pkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_games"
      ADD CONSTRAINT "poster_pixels_games_pkey" PRIMARY KEY ("id");
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint 
    WHERE conname = 'poster_pixels_guesses_pkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_guesses"
      ADD CONSTRAINT "poster_pixels_guesses_pkey" PRIMARY KEY ("id");
  END IF;
END $$;

-- Foreign keys (only add if missing)
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'poster_pixels_games_user_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_games"
      ADD CONSTRAINT "poster_pixels_games_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'poster_pixels_games_puzzle_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_games"
      ADD CONSTRAINT "poster_pixels_games_puzzle_id_fkey" FOREIGN KEY ("puzzle_id") REFERENCES "public"."poster_pixels_puzzles"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'poster_pixels_guesses_user_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_guesses"
      ADD CONSTRAINT "poster_pixels_guesses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'poster_pixels_guesses_puzzle_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_guesses"
      ADD CONSTRAINT "poster_pixels_guesses_puzzle_id_fkey" FOREIGN KEY ("puzzle_id") REFERENCES "public"."poster_pixels_puzzles"("id") ON DELETE CASCADE;
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'poster_pixels_guesses_game_id_fkey'
  ) THEN
    ALTER TABLE ONLY "public"."poster_pixels_guesses"
      ADD CONSTRAINT "poster_pixels_guesses_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."poster_pixels_games"("id") ON DELETE CASCADE;
  END IF;
END $$;

CREATE INDEX IF NOT EXISTS "poster_pixels_puzzles_puzzle_date_idx" ON "public"."poster_pixels_puzzles" USING btree ("puzzle_date");
CREATE INDEX IF NOT EXISTS "poster_pixels_games_user_id_idx" ON "public"."poster_pixels_games" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_games_puzzle_id_idx" ON "public"."poster_pixels_games" USING btree ("puzzle_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_guesses_user_id_idx" ON "public"."poster_pixels_guesses" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_guesses_puzzle_id_idx" ON "public"."poster_pixels_guesses" USING btree ("puzzle_id");

-- 2) Admin fields and structure on puzzles
ALTER TABLE "public"."poster_pixels_puzzles"
  ADD COLUMN IF NOT EXISTS "puzzle_number" INTEGER,
  ADD COLUMN IF NOT EXISTS "film_id" INTEGER,
  ADD COLUMN IF NOT EXISTS "film_title" VARCHAR,
  ADD COLUMN IF NOT EXISTS "film_poster_url" TEXT,
  ADD COLUMN IF NOT EXISTS "film_release_year" INTEGER,
  ADD COLUMN IF NOT EXISTS "clarity_levels" JSONB DEFAULT '[5, 15, 35, 65, 100]'::jsonb,
  ADD COLUMN IF NOT EXISTS "seed_value" VARCHAR(32),
  ADD COLUMN IF NOT EXISTS "difficulty_level" INTEGER DEFAULT 1,
  ADD COLUMN IF NOT EXISTS "fun_fact" TEXT,
  ADD COLUMN IF NOT EXISTS "is_published" BOOLEAN NOT NULL DEFAULT false;

-- allow NULL dates (drafts), unique only for published
DO $$ BEGIN
  BEGIN
    ALTER TABLE "public"."poster_pixels_puzzles" ALTER COLUMN "puzzle_date" DROP NOT NULL;
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;

-- sequence for puzzle_number
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_sequences WHERE schemaname='public' AND sequencename='poster_pixels_puzzles_puzzle_number_seq') THEN
    CREATE SEQUENCE "public"."poster_pixels_puzzles_puzzle_number_seq" AS integer START WITH 1 INCREMENT BY 1;
    ALTER SEQUENCE "public"."poster_pixels_puzzles_puzzle_number_seq" OWNER TO "postgres";
    ALTER SEQUENCE "public"."poster_pixels_puzzles_puzzle_number_seq" OWNED BY "public"."poster_pixels_puzzles"."puzzle_number";
    ALTER TABLE "public"."poster_pixels_puzzles" ALTER COLUMN "puzzle_number" SET DEFAULT nextval('"public"."poster_pixels_puzzles_puzzle_number_seq"'::regclass);
  END IF;
END $$;

CREATE UNIQUE INDEX IF NOT EXISTS "poster_pixels_puzzles_published_date_unique" ON "public"."poster_pixels_puzzles" ("puzzle_date") WHERE "puzzle_date" IS NOT NULL AND "is_published" = TRUE;

-- RLS and grants
ALTER TABLE "public"."poster_pixels_puzzles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."poster_pixels_games" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."poster_pixels_guesses" ENABLE ROW LEVEL SECURITY;

-- Policies: drop if exists then create
DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can view published puzzles" ON "public"."poster_pixels_puzzles";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can view published puzzles" ON "public"."poster_pixels_puzzles"
  FOR SELECT
  USING ("is_published" = TRUE OR EXISTS (SELECT 1 FROM "public"."cinamini_user_profiles" WHERE "user_id" = auth.uid() AND "is_super_admin" = TRUE));

DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can view own games" ON "public"."poster_pixels_games";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can view own games" ON "public"."poster_pixels_games"
  FOR SELECT USING (auth.uid() = user_id);

DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can create own games" ON "public"."poster_pixels_games";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can create own games" ON "public"."poster_pixels_games"
  FOR INSERT WITH CHECK (auth.uid() = user_id);

DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can update own games" ON "public"."poster_pixels_games";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can update own games" ON "public"."poster_pixels_games"
  FOR UPDATE USING (auth.uid() = user_id);

DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can view own guesses" ON "public"."poster_pixels_guesses";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can view own guesses" ON "public"."poster_pixels_guesses"
  FOR SELECT USING (auth.uid() = user_id);

DO $$ BEGIN
  BEGIN
    DROP POLICY IF EXISTS "Users can create own guesses" ON "public"."poster_pixels_guesses";
  EXCEPTION WHEN OTHERS THEN NULL; END;
END $$;
CREATE POLICY "Users can create own guesses" ON "public"."poster_pixels_guesses"
  FOR INSERT WITH CHECK (auth.uid() = user_id);

GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "service_role";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "service_role";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "service_role";

-- 3) Backfill existing data to reflect zoom-first model (safe even if empty)
WITH earliest AS (
  SELECT g.id, g.game_id
  FROM public.poster_pixels_guesses g
  JOIN (
    SELECT game_id, MIN(guess_number) AS min_guess
    FROM public.poster_pixels_guesses
    GROUP BY game_id
  ) m
  ON g.game_id = m.game_id AND g.guess_number = m.min_guess
)
UPDATE public.poster_pixels_guesses gg
SET is_correct = TRUE,
    guess_number = 1
FROM earliest e
WHERE gg.id = e.id;

UPDATE public.poster_pixels_games pg
SET completed = TRUE,
    won = TRUE,
    end_time = COALESCE(end_time, NOW()),
    total_time_ms = 0,
    num_guesses = 1,
    final_clarity_level = 0.05
WHERE EXISTS (
  SELECT 1 FROM public.poster_pixels_guesses g
  WHERE g.game_id = pg.id
);

COMMIT;
