-- Add Poster Pixels game tables

-- Create poster_pixels_puzzles table
CREATE TABLE IF NOT EXISTS "public"."poster_pixels_puzzles" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "puzzle_date" date NOT NULL,
    "movie_data" jsonb NOT NULL,
    "created_at" timestamp with time zone DEFAULT now(),
    "updated_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."poster_pixels_puzzles" OWNER TO "postgres";

-- Create poster_pixels_guesses table  
CREATE TABLE IF NOT EXISTS "public"."poster_pixels_guesses" (
    "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "user_id" uuid NOT NULL,
    "puzzle_id" bigint NOT NULL,
    "game_id" uuid NOT NULL,
    "guess_number" integer NOT NULL,
    "guessed_movie_id" integer,
    "guessed_movie_title" text,
    "is_correct" boolean NOT NULL,
    "time_taken_ms" integer NOT NULL,
    "clarity_level" numeric(3,2) NOT NULL,
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."poster_pixels_guesses" OWNER TO "postgres";

-- Create poster_pixels_games table
CREATE TABLE IF NOT EXISTS "public"."poster_pixels_games" (
    "id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "user_id" uuid NOT NULL,
    "puzzle_id" bigint NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone,
    "completed" boolean DEFAULT false,
    "won" boolean DEFAULT false,
    "total_time_ms" integer,
    "num_guesses" integer DEFAULT 0,
    "final_clarity_level" numeric(3,2),
    "created_at" timestamp with time zone DEFAULT now()
);

ALTER TABLE "public"."poster_pixels_games" OWNER TO "postgres";

-- Add primary keys
ALTER TABLE ONLY "public"."poster_pixels_puzzles"
    ADD CONSTRAINT "poster_pixels_puzzles_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."poster_pixels_guesses"
    ADD CONSTRAINT "poster_pixels_guesses_pkey" PRIMARY KEY ("id");

ALTER TABLE ONLY "public"."poster_pixels_games"
    ADD CONSTRAINT "poster_pixels_games_pkey" PRIMARY KEY ("id");

-- Add unique constraint for one puzzle per day
ALTER TABLE ONLY "public"."poster_pixels_puzzles"
    ADD CONSTRAINT "poster_pixels_puzzles_puzzle_date_key" UNIQUE ("puzzle_date");

-- Add foreign key constraints
ALTER TABLE ONLY "public"."poster_pixels_guesses"
    ADD CONSTRAINT "poster_pixels_guesses_puzzle_id_fkey" FOREIGN KEY ("puzzle_id") REFERENCES "public"."poster_pixels_puzzles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."poster_pixels_guesses"
    ADD CONSTRAINT "poster_pixels_guesses_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."poster_pixels_guesses"
    ADD CONSTRAINT "poster_pixels_guesses_game_id_fkey" FOREIGN KEY ("game_id") REFERENCES "public"."poster_pixels_games"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."poster_pixels_games"
    ADD CONSTRAINT "poster_pixels_games_puzzle_id_fkey" FOREIGN KEY ("puzzle_id") REFERENCES "public"."poster_pixels_puzzles"("id") ON DELETE CASCADE;

ALTER TABLE ONLY "public"."poster_pixels_games"
    ADD CONSTRAINT "poster_pixels_games_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id") ON DELETE CASCADE;

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS "poster_pixels_puzzles_puzzle_date_idx" ON "public"."poster_pixels_puzzles" USING btree ("puzzle_date");
CREATE INDEX IF NOT EXISTS "poster_pixels_guesses_user_id_idx" ON "public"."poster_pixels_guesses" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_guesses_puzzle_id_idx" ON "public"."poster_pixels_guesses" USING btree ("puzzle_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_games_user_id_idx" ON "public"."poster_pixels_games" USING btree ("user_id");
CREATE INDEX IF NOT EXISTS "poster_pixels_games_puzzle_id_idx" ON "public"."poster_pixels_games" USING btree ("puzzle_id");

-- Enable Row Level Security
ALTER TABLE "public"."poster_pixels_puzzles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."poster_pixels_guesses" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "public"."poster_pixels_games" ENABLE ROW LEVEL SECURITY;

-- Create RLS policies

-- Puzzles are readable by everyone
CREATE POLICY "Puzzles are viewable by everyone" ON "public"."poster_pixels_puzzles"
    FOR SELECT USING (true);

-- Users can only view and create their own guesses
CREATE POLICY "Users can view own guesses" ON "public"."poster_pixels_guesses"
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own guesses" ON "public"."poster_pixels_guesses"
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can only view and manage their own games
CREATE POLICY "Users can view own games" ON "public"."poster_pixels_games"
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can create own games" ON "public"."poster_pixels_games"
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own games" ON "public"."poster_pixels_games"
    FOR UPDATE USING (auth.uid() = user_id);

-- Grant necessary permissions
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_puzzles" TO "service_role";

GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_guesses" TO "service_role";

GRANT ALL ON TABLE "public"."poster_pixels_games" TO "postgres";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "anon";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "authenticated";
GRANT ALL ON TABLE "public"."poster_pixels_games" TO "service_role";

-- Add function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create trigger for updated_at
CREATE TRIGGER update_poster_pixels_puzzles_updated_at BEFORE UPDATE ON "public"."poster_pixels_puzzles"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();